version: '3'

services:

  pz:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - mariadb
      - pushgateway
    environment:
      DB_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht"
      PUSHGATEWAY: "http://pushgateway:9091"
    command:
      - /bin/bash

  test:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - mariadb
      - pushgateway
    environment:
      - DB_CONNECTION_STRING="mysql2://ht_rights:ht_rights@mariadb/ht"
      - PUSHGATEWAY="http://pushgateway:9091"
      # pass through info needed by coveralls uploader
      - GITHUB_TOKEN
      - GITHUB_RUN_ID
      - GITHUB_EVENT_TOKEN
      - GITHUB_EVENT_PATH
      - GITHUB_SHA
      - GITHUB_REF
      - GITHUB_ACTIONS
    command: bin/wait-for mariadb:3306 pushgateway:9091 -- prove

  mariadb:
    image: ghcr.io/hathitrust/db-image:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1 
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights

  pushgateway:
    image: prom/pushgateway
