---

x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:
  pz:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      mariadb: *healthy
      pushgateway: *healthy
    environment:
      DATA_ROOT: "/usr/src/app/data"
      POST_ZEPHIR_PROCESSING_LOGGER_LEVEL: "1"
      PUSHGATEWAY: "http://pushgateway:9091"
    command:
      - /bin/bash

  test:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      mariadb: *healthy
      pushgateway: *healthy
    environment:
      - DATA_ROOT=/usr/src/app/data
      - POST_ZEPHIR_PROCESSING_LOGGER_LEVEL=1
      - PUSHGATEWAY="http://pushgateway:9091"
      - MARIADB_HT_RO_USERNAME=ht_rights
      - MARIADB_HT_RO_PASSWORD=ht_rights
      - MARIADB_HT_RO_HOST=mariadb
      - MARIADB_HT_RO_DATABASE=ht
      - MARIADB_RIGHTS_RW_USERNAME=ht_rights
      - MARIADB_RIGHTS_RW_PASSWORD=ht_rights
      - MARIADB_RIGHTS_RW_HOST=mariadb
      - MARIADB_RIGHTS_RW_DATABASE=ht
      # pass through info needed by coveralls uploader
      - GITHUB_TOKEN
      - GITHUB_RUN_ID
      - GITHUB_EVENT_TOKEN
      - GITHUB_EVENT_PATH
      - GITHUB_SHA
      - GITHUB_REF
      - GITHUB_ACTIONS
    command: prove

  mariadb:
    image: ghcr.io/hathitrust/db-image:latest
    volumes:
      - ./sql/ingest.sql:/docker-entrypoint-initdb.d/999-ingest.sql
      - ./sql/hathifiles.sql:/docker-entrypoint-initdb.d/999-hathifiles.sql
    restart: always
    environment:
      # setting via MYSQL_ROOT_PASSWORD didn't work; this at least
      # makes it clear that we have to dig out its generated root password
      # from its startup
      MYSQL_RANDOM_ROOT_PASSWORD: 1 
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  pushgateway:
    image: prom/pushgateway
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "pushgateway:9091/-/healthy" ]

volumes:
  gem_cache:
