---

x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:
  pz:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      mariadb: *healthy
      pushgateway: *healthy
    environment:
      DB_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht"
      PUSHGATEWAY: "http://pushgateway:9091"
    command:
      - /bin/bash

  test:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - mariadb
      - pushgateway
    environment:
      - DB_CONNECTION_STRING="mysql2://ht_rights:ht_rights@mariadb/ht"
      - PUSHGATEWAY="http://pushgateway:9091"
      # pass through info needed by coveralls uploader
      - GITHUB_TOKEN
      - GITHUB_RUN_ID
      - GITHUB_EVENT_TOKEN
      - GITHUB_EVENT_PATH
      - GITHUB_SHA
      - GITHUB_REF
      - GITHUB_ACTIONS
    command: prove

  mariadb:
    image: ghcr.io/hathitrust/db-image:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1 
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  pushgateway:
    image: prom/pushgateway
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "pushgateway:9091/-/healthy" ]
