#!/bin/sh

# because curl -n finds the .netrc in the HOME directory
r=`dirname $0`
rootdir=`cd $r && pwd`

conf=$rootdir/../config/.netrc

remote_file=$1
local_file=$2

SERVER=ftps.cdlib.org
#set SERVER=ftps-stg.cdlib.org

echo "server: ${SERVER}, remote file: ${remote_file}, local_file: ${local_file}"
#/l/local/bin/curl -n -k --ftp-ssl --ftp-pasv  ftp://${SERVER}/${remote_file} --out ${local_file}

curl --netrc-file $conf --ssl-reqd --ftp-pasv  ftp://${SERVER}/${remote_file} --out ${local_file}

