#!/bin/bash

conf=$ROOTDIR/config/.netrc


if [ "$#" -eq "1" ]; then 
  infile=$1
  outfile=$1
elif [ "$#" -eq "2" ]; then 
  infile=$1
  outfile=$2
else
  echo "usage: $0 infile [outfile]"
  exit 1
fi

if [[ -v NOSEND ]]; then
  echo "NOSEND is set; not sending $infile to zephir"
  exit
fi

dir='submissions/'

server=ftps.cdlib.org
#set server=ftps-stg.cdlib.org

echo "server is $server, dir is: ${dir}, sending $infile as $outfile"

#/l/local/bin/curl -k -n -T $infile --ftp-ssl --ftp-pasv ftp://$server/submissions/$outfile

curl --netrc-file $conf -T $infile --ssl-reqd --ftp-pasv ftp://$server/submissions/$outfile
