name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up tests
        run: |
          docker-compose build

      - name: Run tests
        run: docker-compose run test bin/test_and_cover.sh
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
